/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class SecurityFilters {
    def filters = {
		/*主页，退出*/
		pinying(controller: "pinying", action: "*"){
			before={
				accessControl{true}
			}
		}
		/*登录，退出*/
		auth(controller: "auth", action: "*"){
			before={
				accessControl{true}
			}
		}
		
		/*其它*/
		all(controller: "*", action: "*"){
			before={
				accessControl{
					permission("${controllerName}:${actionName}:${params.id}")
				}
			}
		}
    }
}
